backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Work"
    name: "work"
    folder: "src/posts"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Company", name: "company", widget: "string" }
      - { label: "Language", name: "language", widget: "string" }
      - { label: "Icon", name: "icon", widget: "string" }
      - { label: "Link Icon", name: "link_icon", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Display Link", name: "display_link", widget: "string" }
      - { label: "Published", name: "published", widget: "datetime" }
      - { label: "Updated", name: "updated", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: false
        create: true
        options: ["work", "project"]
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Introduction"
        name: "paragraphs"
        file: "src/_data/introduction.yaml"
        fields:
          - label: Introduction
            name: paragraphs
            widget: list
            allow_add: true 
            collapsed: false
            fields:
              - { label: Text, name: text, widget: string }
              - { label: Display Order, name: display-order, widget: string }
      - label: "Langauge Stack"
        name: "languages"
        file: "src/_data/stack.yaml"
        fields:
          - label: Language Stack
            name: languages
            widget: list
            allow_add: true 
            collapsed: false
            fields:
              - { label: Text, name: text, widget: string }
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
